# Generated by Django 6.0.1 on 2026-01-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(default='Dataset Baru', max_length=100)),
                ('file_csv', models.FileField(upload_to='datasets/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nama_user', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('bmi_score', models.FloatField()),
                ('bmi_category', models.CharField(max_length=50)),
                ('hasil_prediksi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jumlah_data', models.IntegerField()),
                ('best_k', models.IntegerField()),
                ('akurasi', models.FloatField()),
                ('train_akurasi', models.FloatField(default=0)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
