# Generated by Django 6.0.1 on 2026-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='activity_level',
            field=models.IntegerField(default=1),
        ),
    ]
