# Generated by Django 6.0.1 on 2026-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_predictionlog_activity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(help_text="Harus SAMA PERSIS dengan label hasil prediksi (misal: 'Cardio')", max_length=100, unique=True)),
                ('deskripsi', models.TextField()),
                ('contoh_gerakan', models.TextField(help_text='Pisahkan gerakan dengan Enter')),
                ('saran_durasi', models.CharField(default='30-45 Menit', max_length=100)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='olahraga/')),
            ],
        ),
    ]
