# Generated by Django 6.0.1 on 2026-01-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0003_detaillatihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillatihan',
            name='contoh_gerakan',
            field=models.TextField(help_text='Pisahkan dengan Enter'),
        ),
        migrations.AlterField(
            model_name='detaillatihan',
            name='deskripsi',
            field=models.TextField(verbose_name='Penjelasan'),
        ),
        migrations.AlterField(
            model_name='detaillatihan',
            name='nama_kategori',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('Low Impact Cardio', 'Low Impact Cardio'), ('Water Aerobics', 'Water Aerobics'), ('Weight Gain Program', 'Weight Gain Program'), ('Medical Supervised Workouts', 'Medical Supervised Workouts'), ('Low Impact Workouts', 'Low Impact Workouts')], max_length=100, unique=True, verbose_name='Jenis Olahraga Satuan'),
        ),
    ]
